name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/amiw-bot

            # Write secrets to .env
            echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
            echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> .env

            # Pull latest code
            git reset --hard
            git pull origin main

            # Install dependencies
            npm install

            # Compile TypeScript
            npx tsc

            # Restart bot
            pm2 restart amiw-bot || pm2 start dist/index.js --name amiw-bot
